name: Arduino Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: arduino-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run arduino-lint
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: specification
          project-type: library
